# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22fe3740ac6118cd595fcfd4194869e402ee6b30820900c93d0150ee8abdfcdcee481ebd8ecc1f26b7675bbb53a49053e49682ad1cbf053e1752ae13c687b805

test:
  secret_key_base: 89d1604bf1a555664cfe87a2ff912a9ada3aa08030688fcef0fd49358f176e6fc48160f0414f6b681f4cc8a6f4b47c18ca8aec85e39ad6e0caf1043410b75c3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
